locals {
  default_resource_codes = merge(local.default_azure_resource_codes, local.default_aws_resource_codes)

  default_azure_resource_codes = {
    # AI and machine learning
    ai_search                   = "srch"
    foundry_tools_multi_service = "ais"
    foundry_account             = "aif"
    foundry_account_project     = "proj"
    foundry_hub                 = "hub"
    foundry_hub_project         = "proj"
    ai_video_indexer            = "avi"
    machine_learning_workspace  = "mlw"
    azure_openai_service        = "oai"
    bot_service                 = "bot"
    computer_vision             = "cv"
    content_moderator           = "cm"
    content_safety              = "cs"
    custom_vision_prediction    = "cstv"
    custom_vision_training      = "cstvt"
    document_intelligence       = "di"
    face_api                    = "face"
    health_insights             = "hi"
    immersive_reader            = "ir"
    language_service            = "lang"
    speech_service              = "spch"
    translator                  = "trsl"

    # Analytics and IoT
    analysis_services_server         = "as"
    databricks_access_connector      = "dbac"
    databricks_workspace             = "dbw"
    kusto_cluster                    = "dec"
    kusto_database                   = "dedb"
    data_factory                     = "adf"
    digital_twin_instance            = "dt"
    stream_analytics                 = "asa"
    synapse_private_link_hub         = "synplh"
    synapse_sql_pool                 = "syndp"
    synapse_spark_pool               = "synsp"
    synapse_workspace                = "synw"
    data_lake_store_account          = "dls"
    eventhub_namespace               = "evhns"
    eventhub                         = "evh"
    eventgrid_domain                 = "evgd"
    eventgrid_namespace              = "evgns"
    eventgrid_event_subscription     = "evgs"
    eventgrid_topic                  = "evgt"
    eventgrid_system_topic           = "egst"
    fabric_capacity                  = "fc"
    hdinsight_hadoop_cluster         = "hadoop"
    hdinsight_hbase_cluster          = "hbase"
    hdinsight_kafka_cluster          = "kafka"
    hdinsight_spark_cluster          = "spark"
    hdinsight_storm_cluster          = "storm"
    hdinsight_ml_services_cluster    = "mls"
    iothub                           = "iot"
    provisioning_service             = "provs"
    provisioning_service_certificate = "pcert"
    power_bi_embedded                = "pbi"
    time_series_insights_environment = "tsi"

    # Compute and web
    app_service_environment                   = "ase"
    app_service_plan                          = "asp"
    load_testing_instance                     = "lt"
    availability_set                          = "avail"
    arc_enabled_server                        = "arcs"
    arc_enabled_kubernetes_cluster            = "arck"
    arc_private_link_scope                    = "pls"
    arc_gateway                               = "arcgw"
    batch_account                             = "ba"
    cloud_service                             = "cld"
    communication_services                    = "acs"
    disk_encryption_set                       = "des"
    function_app                              = "func"
    shared_image_gallery                      = "gal"
    gallery                                   = "gal"
    hosting_environment                       = "host"
    image_template                            = "it"
    managed_disk_os                           = "osdisk"
    managed_disk_data                         = "disk"
    notification_hub                          = "ntf"
    notification_hub_namespace                = "ntfns"
    proximity_placement_group                 = "ppg"
    restore_point_collection                  = "rpc"
    snapshot                                  = "snap"
    static_site                               = "stapp"
    virtual_machine                           = "vm"
    virtual_machine_scale_set                 = "vmss"
    virtual_machine_maintenance_configuration = "mc"
    storage_account_vm                        = "stvm"
    web_app                                   = "app"

    # Containers
    kubernetes_cluster             = "aks"
    aks_cluster                    = "aks"
    aks_system_node_pool           = "npsystem"
    aks_user_node_pool             = "np"
    container_app                  = "ca"
    container_app_environment      = "cae"
    container_app_job              = "caj"
    container_registry             = "cr"
    container_instance             = "ci"
    container_group                = "ci"
    service_fabric_cluster         = "sf"
    service_fabric_managed_cluster = "sfmc"

    # Databases
    cosmosdb_database           = "cosmos"
    cosmosdb_account            = "cosmos"
    cosmosdb_cassandra_account  = "coscas"
    cosmosdb_mongodb_account    = "cosmon"
    cosmosdb_nosql_account      = "cosno"
    cosmosdb_table_account      = "costab"
    cosmosdb_gremlin_account    = "cosgrm"
    cosmosdb_postgresql_cluster = "cospos"
    azure_managed_redis         = "amr"
    redis_cache                 = "redis"
    sql_server                  = "sql"
    sql_database                = "sqldb"
    sql_elastic_job_agent       = "sqlja"
    sql_elasticpool             = "sqlep"
    mysql_server                = "mysql"
    mysql_database              = "mysqldb"
    postgres_server             = "psql"
    postgresql_database         = "psql"
    sql_managed_database        = "sqlmdb"
    sql_managed_instance        = "sqlmi"

    # Developer tools and DevOps
    app_configuration   = "appcs"
    maps_account        = "map"
    signalr_service     = "sigr"
    webpubsub           = "wps"
    managed_grafana     = "amg"
    managed_devops_pool = "mdp"

    # General, integration, management, and governance
    api_management                = "apim"
    api_management_service        = "apim"
    integration_account           = "ia"
    logic_app_integration_account = "ia"
    logic_app_workflow            = "logic"
    servicebus_namespace          = "sbns"
    servicebus_queue              = "sbq"
    servicebus_topic              = "sbt"
    servicebus_topic_subscription = "sbts"
    automation_account            = "aa"
    policy_definition             = "policy"
    application_insights          = "appi"
    monitor_action_group          = "ag"
    monitor_data_collection_rule  = "dcr"
    monitor_alert_processing_rule = "apr"
    data_collection_endpoint      = "dce"
    deployment_script             = "script"
    log_analytics_workspace       = "log"
    log_analytics_query_pack      = "pack"
    management_group              = "mg"
    purview_account               = "pview"
    resource_group                = "rg"
    template_spec                 = "ts"
    monitor_metric_alert          = "azalert"
    monitor_diagnostics_setting   = "ds"
    blueprint_definition          = "bp"
    blueprint_assignment          = "bpa"
    log_analytics_cluster         = "logc"
    log_analytics_solution        = "logs"

    # Migration
    migrate_project            = "migr"
    database_migration_project = "migr"
    database_migration_service = "dms"
    recovery_services_vault    = "rsv"

    # Networking
    application_gateway                    = "agw"
    application_security_group             = "asg"
    cdn_profile                            = "cdnp"
    cdn_endpoint                           = "cdne"
    connection                             = "con"
    dns_zone                               = "dnsz"
    dns_forwarding_ruleset                 = "dnsfrs"
    dns_private_resolver                   = "dnspr"
    dns_private_resolver_inbound_endpoint  = "in"
    dns_private_resolver_outbound_endpoint = "out"
    private_dns_zone                       = "pdnsz"
    firewall                               = "afw"
    firewall_policy                        = "afwp"
    express_route_circuit                  = "erc"
    express_route_direct                   = "erd"
    express_route_gateway                  = "ergw"
    frontdoor                              = "afd"
    frontdoor_endpoint                     = "fde"
    frontdoor_firewall_policy              = "fdfp"
    ip_group                               = "ipg"
    lb_internal                            = "lbi"
    lb_external                            = "lbe"
    lb_rule                                = "rule"
    local_network_gateway                  = "lgw"
    nat_gateway                            = "ng"
    network_ddos_protection_plan           = "dosp"
    network_interface                      = "nic"
    network_security_perimeter             = "nsp"
    network_security_group                 = "nsg"
    network_security_rule                  = "nsgsr"
    network_watcher                        = "nw"
    private_link_service                   = "pl"
    private_endpoint                       = "pep"
    public_ip                              = "pip"
    public_ip_prefix                       = "ippre"
    route_filter                           = "rf"
    route_server                           = "rtserv"
    route_table                            = "rt"
    service_endpoint                       = "se"
    service_endpoint_policy                = "se"
    traffic_manager_profile                = "traf"
    route                                  = "udr"
    virtual_network                        = "vnet"
    virtual_network_gateway                = "vgw"
    virtual_network_manager                = "vnm"
    virtual_network_peering                = "peer"
    subnet                                 = "snet"
    virtual_wan                            = "vwan"
    virtual_hub                            = "vhub"

    # Security
    bastion_host                          = "bas"
    key_vault                             = "kv"
    key_vault_managed_hsm                 = "kvmhsm"
    managed_identity                      = "id"
    user_assigned_identity                = "id"
    ssh_key                               = "sshkey"
    vpn_gateway                           = "vpng"
    vpn_gateway_connection                = "vcn"
    vpn_site                              = "vst"
    web_application_firewall_policy       = "waf"
    firewall_policy_rule_collection_group = "wafrg"

    # Storage
    backup_resource_guard = "rgd"
    backup_vault          = "bvault"
    backup_vault_policy   = "bkpol"
    file_share            = "share"
    storage_account       = "st"
    storage_account_blob  = "blob"
    storage_sync_service  = "sss"

    # Virtual desktop infrastructure
    virtual_desktop_host_pool         = "vdpool"
    virtual_desktop_application_group = "vdag"
    virtual_desktop_workspace         = "vdws"
    virtual_desktop_scaling_plan      = "vdscaling"
  }
}
